### ISSUE TITLE
VS2019 and VS2017 build fails on Visual Studio Setup

### ISSUE THREAD

**Issue by TheDanielDoyle** [nventive/docker#4]
First off, thank you for sharing this fantastic docker setup. You've saved me a lot of time, and i thank you!

I've tried building on Windows Sever 2019 1809 and Windows 10 Enterprise 1903 but no luck.
This also affects the VS2017 build.

The log is below:

`docker build -m 4G -f vs16_enterprise.dockerfile .`

`Sending build context to Docker daemon  90.62kB
Step 1/20 : FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
 ---> 556ff004bdf0
Step 2/20 : COPY [ "ImageHelpers", "C:/Program Files/WindowsPowerShell/Modules/ImageHelpers/"]
 ---> Using cache
 ---> 4afb7036c571
Step 3/20 : COPY Scripts\ C:\Scripts\
 ---> Using cache
 ---> 5bc0512aa014
Step 4/20 : RUN powershell -Command "C:\Scripts\VS2019\Initialize-VM.ps1"
 ---> Using cache
 ---> ae32eb9547a0
Step 5/20 : RUN powershell -Command "C:\Scripts\VS2019\Install-VisualStudio.ps1"
 ---> Running in ff3a29befe67
Enable short name support on Windows needed for Xamarin Android AOT, defaults appear to have been changed in Azure VMs
Downloading Bootstrapper ...
Starting Install ...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1028\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\2052\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1042\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1029\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1036\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\3082\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1040\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1031\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1045\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1041\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1055\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1046\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1049\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\HelpFile\1033\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\vs_setup_bootstrapper.exe...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\Microsoft.Diagnostics.Tracing.EventSource.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\Microsoft.VisualStudio.RemoteControl.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup.Common.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup.Download.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\Microsoft.VisualStudio.Telemetry.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\Microsoft.VisualStudio.Utilities.Internal.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\Newtonsoft.Json.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\zh-Hans\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\zh-Hant\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\cs\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\de\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\pl\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\es\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\it\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\ko\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\fr\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\ja\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\pt-BR\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\tr\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\ru\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\vs_setup_bootstrapper.config...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\vs_setup_bootstrapper.exe.config...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\detection.json...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\76130d82db64b02742ee22fbb9752d\vs_bootstrapper_d15\vs_setup_bootstrapper.json...
Non zero exit code returned by the installation process : 1.
The command 'cmd /S /C powershell -Command "C:\Scripts\VS2019\Install-VisualStudio.ps1"' returned a non-zero code: 1`

**Comment by TheDanielDoyle** [comment]
Hi, I managed to get past the issue by increasing the max image size in the docker options.

**Comment by benventive** [comment]
Hi @TheDanielDoyle, thank you for using it! 
I've encountered that issue and I think I'll try and update the Install-VisualStudio.ps1 script so it grabs the actual error message from the log file. I'll update the documentation to add this.
